### PR TITLE
Travel website

### PR DESCRIPTION
**Pull request by Sady-dotcom**
This pull request includes a change of the PR title and a new description. Borders are removed and hero picture is aligned to center.

### CODE REVIEW

**Review by Devsalmasaeed — CHANGES_REQUESTED** [review]
Hi @Sady-dotcom ,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️
- Please used professional PR title and description
- Make sure this images are centrally aligned
Screenshot (12)
-  Please remove the borders
Screenshot (13)
Screenshot (14)
Screenshot (15)


 

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @Sady-dotcom 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Please correct the changes in the sections below
- 
image
- remove the border around the text
- 
image
- Add gaps between the cards in this section
- 
image
- make the divider images 100% to avoid the your website overflowing

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by Sady-dotcom** [comment]
@Xfarouq updated pull request with the corrections. Border around text removed, gaps added between the cards and divider image width to 100%.

**Review by Devsalmasaeed — APPROVED** [review]
Hi @Sady-dotcom ,

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    Remote Collaboration
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Pull request merged**
